#!/usr/bin/python2.7 -tt

def IsEndOfMessage(message, message_termination):
    if len(message) >= len(message_termination):
        if message[-len(message_termination):] == message_termination:
            return True
    return False

def RecieveMessage(buffer_size):
    whole_message = ''
    end_of_message = False
    while not end_of_message:
        whole_message += server.recv(buffer_size)
        end_of_message = IsEndOfMessage(whole_message, message_termination)
    return whole_message

from socket import *

RECIEVE_BUFFER_SIZE = 1024
IP = 'localhost'
message_termination = "\r\n\r\n"
requested_url = "/counter"

server_port_file = open("server_port", "r")
server_port = int(server_port_file.read())
server_port_file.close()
counter = 0

server = socket()
server.connect((IP, server_port))
while True:
    whole_message = RecieveMessage(RECIEVE_BUFFER_SIZE)
    counter += 1
    first_line = whole_message.split("\r\n")[0]
    if first_line.split(" ")[1] == requested_url:
        reply = "HTTP/1.0 200 OK\r\nContent-Type: text/html\r\nContent-Length: {0}\r\n\r\n{1}\r\n\r\n".format(len(str(counter)), counter)
        server.send(reply)